### ISSUE TITLE
function_runner_with_pdb: drop to ipdb on BaseException as well - 86

### ISSUE THREAD

**Issue by redhat-qe-bot2** [RedHatQE/pyhelper-utils#87]
[Auto generated]
Number: [#86]

**Comment by msi-b1** [comment]
[38;5;148mpyhelper-utils[0m[pull_request][5958-11ef-891e-6a4603f01847][PR 86]: Closing issue for PR: function_runner_with_pdb: drop to ipdb on BaseException as well.
PR was closed.
